# Generated by Django 6.0.7 on 2026-08-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'projects',
            '0004_alter_activitylog_project_alter_activitylog_task_and_more'
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='organizations.organization',
            ),
        ),

        migrations.AlterField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='organizations.organization',
            ),
        ),
    ]