# Generated by Django 6.0.7 on 2026-07-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_taskactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TaskActivity',
        ),
    ]
