# Generated by Django 6.0.7 on 2026-08-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_team_remove_projectmember_unique_project_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.team'),
        ),
    ]
