# Generated by Django 6.0.7 on 2026-07-30 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_due_date_project_members_project_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='projects.task'),
        ),
    ]
