# Generated by Django 6.0.7 on 2026-08-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_task_description'),
        ('projects', '0012_alter_task_assigned_to'),
    ]

    operations = [
    ]
