# Generated by Django 6.0.7 on 2026-08-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='organizations.organization',
                null=True,
                blank=True,
            ),
        ),
    ]