# Generated by Django 6.0.7 on 2026-07-29 06:23

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_email_notifications_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[accounts.validators.validate_file_size, accounts.validators.validate_image_extension]),
        ),
    ]
