# Generated by Django 6.0.7 on 2026-08-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
