# Generated by Django 6.0.7 on 2026-08-03 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_role_is_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvitation',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
