# Generated by Django 6.0.7 on 2026-08-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_userinvitation_expires_at_userinvitation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
