# Generated by Django 6.0.7 on 2026-08-07 08:57

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=models.SET_NULL,
                to="organizations.organization",
    ),
)
    ]
