from .views import (
    LoginAPIView,
    ProfileAPIView,
    LogoutAPIView,
    OrganizationListCreateAPIView,
    OrganizationDetailAPIView,
    UserListAPIView,
    UserDetailAPIView,
    UserUpdateAPIView,
    UserStatusAPIView,
    UserRemoveAPIView,
    RoleListAPIView,
    RoleDetailAPIView,
    RoleCreateAPIView,
    RoleUpdateAPIView,
    RoleDeleteAPIView,
    PermissionListAPIView,
    RolePermissionUpdateAPIView,
    TokenRefreshAPIView,
    ProfileImageUploadAPIView,
    OrganizationLogoUploadAPIView,
)

from django.urls import path


urlpatterns = [

    path(
        "auth/login/",
        LoginAPIView.as_view(),
        name="api-login"
    ),

    path(
        "auth/profile/",
        ProfileAPIView.as_view(),
        name="api-profile"
    ),

    path(
        "auth/logout/",
        LogoutAPIView.as_view(),
        name="api-logout"
    ),
    path(
    "organizations/",
    OrganizationListCreateAPIView.as_view(),
    name="organization-list-create",
),

path(
    "organizations/<int:pk>/",
    OrganizationDetailAPIView.as_view(),
    name="organization-detail",
),
path(
    "users/",
    UserListAPIView.as_view(),
    name="user-list",
),

path(
    "users/<int:pk>/",
    UserDetailAPIView.as_view(),
    name="user-detail",
),
path(
    "users/<int:pk>/update/",
    UserUpdateAPIView.as_view(),
    name="user-update",
),
path(
    "users/<int:pk>/status/",
    UserStatusAPIView.as_view(),
    name="user-status"
),
path(
    "users/<int:pk>/remove/",
    UserRemoveAPIView.as_view(),
    name="user-remove"
),
path(
    "roles/",
    RoleListAPIView.as_view(),
    name="role-list",
),
path(
    "roles/<int:pk>/",
    RoleDetailAPIView.as_view(),
    name="role-detail",
),
path(
    "roles/create/",
    RoleCreateAPIView.as_view(),
    name="role-create",
),
path(
    "roles/<int:pk>/update/",
    RoleUpdateAPIView.as_view(),
    name="role-update",
),
path(
    "roles/<int:pk>/delete/",
    RoleDeleteAPIView.as_view(),
    name="role-delete",
),
path(
    "permissions/",
    PermissionListAPIView.as_view(),
    name="permission-list",
),
path(
    "roles/<int:pk>/permissions/",
    RolePermissionUpdateAPIView.as_view(),
    name="role-permissions-update",
),
path(
    "token/refresh/",
    TokenRefreshAPIView.as_view(),
    name="token-refresh",
),
path(
    "profile/image/",
    ProfileImageUploadAPIView.as_view(),
    name="profile-image-upload"
),
path(
    "organization/logo/",
    OrganizationLogoUploadAPIView.as_view(),
    name="organization-logo-upload",
),

]